app:
  debug: true
  chat_id: xxxx
  keep_alive_chat_id: xxxx
  token: xx

keys:
  bot_name: 卫小兵
  weather_key: xxxxxxxxxxx # 高德天气 api key
  tianapi_key: xxxxxxxxxxxx # 天行 api key
  tianapi_key1: xxxxxxxxxxxxxx # 天行 api key
  qweather_key: xxxxxxxxxxxxxxxx # 和风天气 api key
  lover_ch_name: xxxxxx
  remind_msg: xxxx

redis:
  ip: 39.xxxxx
  port: 6379
  passwd: xxxxxx